services:
  - type: web
    name: coachmim-web
    env: python
    plan: starter
    buildCommand: python -m pip install -r requirements.txt && python -m flask --app wsgi.py db upgrade
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: coachMIMdb
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
