services:
  - type: web
    name: coachmim-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: coachMIMdb
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
